apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  project: default
  source:
    repoURL: https://github.com/6620913/airflow-dag.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: pods
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
