apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/6620913/airflow-dag.git
      revision: HEAD
      files:
      - path: "data/list.json"
      
  template:
    metadata:
      name: '{{cluster.name}}'
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated: {}
      source:
        repoURL: https://github.com/6620913/airflow-dag.git
        targetRevision: HEAD
        path: chart
        helm: 
          values: |
              Name: {{cluster.name}}